# Generated by Django 4.0.3 on 2022-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionimages',
            name='image',
            field=models.FileField(upload_to='attimagesm'),
        ),
        migrations.AlterField(
            model_name='parkimages',
            name='image',
            field=models.FileField(upload_to='parksm'),
        ),
    ]
