# Generated by Django 4.0.3 on 2022-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
